import { makeFunctionReference } from "convex/server";

export const convexRefs = {
  queueList: makeFunctionReference<"query">("queue:list"),
  threadsList: makeFunctionReference<"query">("threads:list"),
  threadGet: makeFunctionReference<"query">("threads:get"),
  callsListByThread: makeFunctionReference<"query">("calls:listByThread"),
  callsHasRecentFallbackSend: makeFunctionReference<"query">("calls:hasRecentFallbackSend"),
  threadsGetEligibility: makeFunctionReference<"query">("threads:getEligibility"),
  threadsGetEligibilityByJid: makeFunctionReference<"query">("threads:getEligibilityByJid"),
  followupsList: makeFunctionReference<"query">("followups:list"),
  backlogList: makeFunctionReference<"query">("backlog:list"),
  todosList: makeFunctionReference<"query">("todos:list"),
  rulesList: makeFunctionReference<"query">("rules:list"),
  settingsGet: makeFunctionReference<"query">("settings:get"),
  settingsSaveOnboardingPreset: makeFunctionReference<"mutation">("settings:saveOnboardingPreset"),
  systemHealth: makeFunctionReference<"query">("system:health"),
  systemAdminOverviewMetrics: makeFunctionReference<"query">("system:adminOverviewMetrics"),
  systemSetupStatus: makeFunctionReference<"query">("system:setupStatus"),
  rateLimitsCheck: makeFunctionReference<"mutation">("rateLimits:check"),
  contextConversationHistorySearch: makeFunctionReference<"query">("contextTools:conversationHistorySearch"),
  contextGetMessageEmbeddings: makeFunctionReference<"query">("contextTools:getMessageEmbeddings"),
  contextWindowDetection: makeFunctionReference<"query">("contextTools:contextWindowDetection"),
  contextWindowCleaning: makeFunctionReference<"query">("contextTools:contextWindowCleaning"),
  contextGetThreadOldestMessageForFetch: makeFunctionReference<"query">("contextTools:getThreadOldestMessageForFetch"),
  conversationIntelligenceGetThreadState: makeFunctionReference<"query">("conversationIntelligence:getThreadState"),
  conversationIntelligenceGetReplyGuidance: makeFunctionReference<"query">("conversationIntelligence:getReplyGuidance"),
  conversationIntelligenceRecordReplyGuidance: makeFunctionReference<"mutation">("conversationIntelligence:recordReplyGuidance"),
  chatMemorySearch: makeFunctionReference<"query">("chatTools:memorySearch"),
  chatConversationRecallQuery: makeFunctionReference<"query">("chatTools:conversationRecallQuery"),
  chatGetThreadStyleProfile: makeFunctionReference<"query">("chatTools:getThreadStyleProfile"),
  chatContactMemoryFactsList: makeFunctionReference<"query">("chatTools:contactMemoryFactsList"),
  chatPersonalConnectorsInternalSearch: makeFunctionReference<"query">("chatTools:personalConnectorsInternalSearch"),
  chatReplyStyleGuardrailCheck: makeFunctionReference<"query">("chatTools:replyStyleGuardrailCheck"),
  aiFeedbackGetThreadAdaptiveHints: makeFunctionReference<"query">("aiFeedback:getThreadAdaptiveHints"),
  aiFeedbackGetActiveTuningProfile: makeFunctionReference<"query">("aiFeedback:getActiveTuningProfile"),
  conversationQualityListForAdmin: makeFunctionReference<"query">("conversationQuality:listForAdmin"),
  conversationQualityRunManual: makeFunctionReference<"action">("conversationQualityActions:runManual"),

  inboundIngest: makeFunctionReference<"mutation">("inbound:ingest"),
  inboundAttachMediaAsset: makeFunctionReference<"mutation">("inbound:attachMediaAsset"),
  draftSaveGenerated: makeFunctionReference<"mutation">("draft:saveGenerated"),
  draftSaveOrReplacePending: makeFunctionReference<"mutation">("draft:saveOrReplacePending"),
  draftCreateGuardrailHold: makeFunctionReference<"mutation">("draft:createGuardrailHold"),
  draftApprove: makeFunctionReference<"mutation">("draft:approve"),
  draftSnooze: makeFunctionReference<"mutation">("draft:snooze"),
  followupsConfirm: makeFunctionReference<"mutation">("followups:confirm"),
  backlogRefreshRecent: makeFunctionReference<"mutation">("backlog:refreshRecent"),
  backlogCreateDraft: makeFunctionReference<"mutation">("backlog:createDraft"),
  backlogSetImportanceOverride: makeFunctionReference<"mutation">("backlog:setImportanceOverride"),
  backlogSetRelationshipOverride: makeFunctionReference<"mutation">("backlog:setRelationshipOverride"),
  backlogSnooze: makeFunctionReference<"mutation">("backlog:snooze"),
  backlogUnsnooze: makeFunctionReference<"mutation">("backlog:unsnooze"),
  backlogIgnoreThread: makeFunctionReference<"mutation">("backlog:ignoreThread"),
  todosFromCandidate: makeFunctionReference<"mutation">("todos:fromCandidate"),
  todosCreateAgendaRange: makeFunctionReference<"mutation">("todos:createAgendaRange"),
  rulesUpsertIgnoreRule: makeFunctionReference<"mutation">("rules:upsertIgnoreRule"),
  threadsUpsertMetadata: makeFunctionReference<"mutation">("threads:upsertMetadata"),
  threadsUpsertContactMetadata: makeFunctionReference<"mutation">("threads:upsertContactMetadata"),
  threadsGetAvatarCache: makeFunctionReference<"query">("threads:getAvatarCache"),
  threadsUpdateAvatarCache: makeFunctionReference<"mutation">("threads:updateAvatarCache"),
  threadsSetNightPause: makeFunctionReference<"mutation">("threads:setNightPause"),
  threadsListContacts: makeFunctionReference<"query">("threads:listContacts"),
  outreachRunManual: makeFunctionReference<"mutation">("outreach:runManual"),
  callsRecordEvent: makeFunctionReference<"mutation">("calls:recordEvent"),

  outboxClaimDue: makeFunctionReference<"mutation">("outbox:claimDue"),
  outboxMarkTyping: makeFunctionReference<"mutation">("outbox:markTyping"),
  outboxGetSendDisposition: makeFunctionReference<"query">("outbox:getSendDisposition"),
  outboxSuppressForManualIntervention: makeFunctionReference<"mutation">("outbox:suppressForManualIntervention"),
  outboxHydrateAiOutreach: makeFunctionReference<"mutation">("outbox:hydrateAiOutreach"),
  outboxHydrateAiStatus: makeFunctionReference<"mutation">("outbox:hydrateAiStatus"),
  outboxStageStatusReview: makeFunctionReference<"mutation">("outbox:stageStatusReview"),
  outboxRewriteClaimedMessage: makeFunctionReference<"mutation">("outbox:rewriteClaimedMessage"),
  outboxDeferClaimed: makeFunctionReference<"mutation">("outbox:deferClaimed"),
  outboxMarkSent: makeFunctionReference<"mutation">("outbox:markSent"),
  outboxMarkFailed: makeFunctionReference<"mutation">("outbox:markFailed"),

  systemPauseAutonomy: makeFunctionReference<"mutation">("system:pauseAutonomy"),
  systemResumeAutonomy: makeFunctionReference<"mutation">("system:resumeAutonomy"),
  systemRecordEvent: makeFunctionReference<"mutation">("system:recordEvent"),
  systemRecordProviderRun: makeFunctionReference<"mutation">("system:recordProviderRun"),
  systemRecordToolRun: makeFunctionReference<"mutation">("system:recordToolRun"),
  systemUpsertSetupStatus: makeFunctionReference<"mutation">("system:upsertSetupStatus"),
  systemReportSetupListener: makeFunctionReference<"mutation">("system:reportSetupListener"),
  contextUpsertMessageEmbeddings: makeFunctionReference<"mutation">("contextTools:upsertMessageEmbeddings"),
  chatRebuildThreadStyleProfile: makeFunctionReference<"mutation">("chatTools:rebuildThreadStyleProfile"),
  chatUpsertContactMemoryFact: makeFunctionReference<"mutation">("chatTools:upsertContactMemoryFact"),
  chatExtractContactMemoryFacts: makeFunctionReference<"mutation">("chatTools:extractContactMemoryFacts"),
  aiFeedbackRecordSignal: makeFunctionReference<"mutation">("aiFeedback:recordSignal"),
  aiFeedbackRecordCandidateEvals: makeFunctionReference<"mutation">("aiFeedback:recordCandidateEvals"),
  conversationQualityDismissFinding: makeFunctionReference<"mutation">("conversationQuality:dismissFinding"),
  conversationQualityPrepareFindingRun: makeFunctionReference<"mutation">("conversationQuality:prepareFindingRun"),
  conversationQualityMarkFindingRunFinished: makeFunctionReference<"mutation">(
    "conversationQuality:markFindingRunFinished",
  ),

  adminSecretsList: makeFunctionReference<"query">("adminSecrets:list"),
  adminSecretsGetEncrypted: makeFunctionReference<"query">("adminSecrets:getEncrypted"),
  adminSecretsUpsert: makeFunctionReference<"mutation">("adminSecrets:upsert"),
  adminSecretsRemove: makeFunctionReference<"mutation">("adminSecrets:remove"),
  adminUsersHasAny: makeFunctionReference<"query">("adminUsers:hasAny"),
  adminUsersList: makeFunctionReference<"query">("adminUsers:list"),
  adminUsersGetCredential: makeFunctionReference<"query">("adminUsers:getCredential"),
  adminUsersGetCapabilities: makeFunctionReference<"query">("adminUsers:getCapabilities"),
  adminUsersUpsert: makeFunctionReference<"mutation">("adminUsers:upsert"),
  adminUsersRemove: makeFunctionReference<"mutation">("adminUsers:remove"),
  tenantAccountsRegisterFromDesktop: makeFunctionReference<"mutation">("tenantAccounts:registerFromDesktop"),
  tenantAccountsIssueConnectorToken: makeFunctionReference<"mutation">("tenantAccounts:issueConnectorToken"),
  tenantAccountsVerifyConnectorToken: makeFunctionReference<"mutation">("tenantAccounts:verifyConnectorToken"),
  tenantAccountsGetConnectorSelfControlAccess: makeFunctionReference<"mutation">(
    "tenantAccounts:getConnectorSelfControlAccess",
  ),
  tenantAccountsGetLoginPinSalt: makeFunctionReference<"mutation">("tenantAccounts:getLoginPinSalt"),
  tenantAccountsVerifyTenantLogin: makeFunctionReference<"mutation">("tenantAccounts:verifyTenantLogin"),
  tenantAccountsAdminList: makeFunctionReference<"query">("tenantAccounts:adminList"),
  tenantAccountsAdminGet: makeFunctionReference<"query">("tenantAccounts:adminGet"),
  tenantAccountsAdminUpdateSubscription: makeFunctionReference<"mutation">("tenantAccounts:adminUpdateSubscription"),
  tenantAccountsAdminUpsertUser: makeFunctionReference<"mutation">("tenantAccounts:adminUpsertUser"),
  tenantAccountsAdminRemoveUser: makeFunctionReference<"mutation">("tenantAccounts:adminRemoveUser"),
  tenantAccountsAdminSeedOwnerAndBackfill: makeFunctionReference<"mutation">("tenantAccounts:adminSeedOwnerAndBackfill"),
  billingCreateCheckoutFromTenantSession: makeFunctionReference<"mutation">("billing:createCheckoutFromTenantSession"),
  billingAttachCheckoutLinkFromTenantSession: makeFunctionReference<"mutation">("billing:attachCheckoutLinkFromTenantSession"),
  billingRecordFlutterwaveEvent: makeFunctionReference<"mutation">("billing:recordFlutterwaveEvent"),
  billingAdminCreateCheckout: makeFunctionReference<"mutation">("billing:adminCreateCheckout"),
  billingAdminAttachCheckoutLink: makeFunctionReference<"mutation">("billing:adminAttachCheckoutLink"),
  billingAdminRecordFlutterwaveEvent: makeFunctionReference<"mutation">("billing:adminRecordFlutterwaveEvent"),
  billingGetTenantBillingSummary: makeFunctionReference<"query">("billing:getTenantBillingSummary"),
  adminPlatformSubscriptionConfig: makeFunctionReference<"query">("adminPlatform:subscriptionConfig"),
  adminPlatformSaveSubscriptionConfig: makeFunctionReference<"mutation">("adminPlatform:saveSubscriptionConfig"),
  adminPlatformPlatformConfig: makeFunctionReference<"query">("adminPlatform:platformConfig"),
  adminPlatformSavePlatformConfig: makeFunctionReference<"mutation">("adminPlatform:savePlatformConfig"),
  adminPlatformBillingOps: makeFunctionReference<"query">("adminPlatform:billingOps"),
  adminPlatformAuditFeed: makeFunctionReference<"query">("adminPlatform:auditFeed"),
  connectedAccountsUpsertFromConnector: makeFunctionReference<"mutation">("connectedAccounts:upsertFromConnector"),
  connectedAccountsMarkDisconnectedFromConnector: makeFunctionReference<"mutation">(
    "connectedAccounts:markDisconnectedFromConnector",
  ),

  styleGetProfile: makeFunctionReference<"query">("style:getProfile"),
  styleGetStatusVoice: makeFunctionReference<"query">("style:getStatusVoice"),
  styleSetMimicry: makeFunctionReference<"mutation">("style:setMimicry"),
  styleLearnFromHumorSignal: makeFunctionReference<"mutation">("style:learnFromHumorSignal"),
  personalityListProfiles: makeFunctionReference<"query">("personality:listProfiles"),
  personalityGetThreadSetting: makeFunctionReference<"query">("personality:getThreadSetting"),
  personalitySetThreadSetting: makeFunctionReference<"mutation">("personality:setThreadSetting"),
  personalityUpsertProfile: makeFunctionReference<"mutation">("personality:upsertProfile"),
  romanceMorningGetThreadState: makeFunctionReference<"query">("romanceProtocol:getThreadState"),
  romanceMorningRecordHydration: makeFunctionReference<"mutation">("romanceProtocol:recordHydration"),
  relationshipStateGetThreadState: makeFunctionReference<"query">("relationshipState:getThreadState"),
  relationshipStateListByPriorityTier: makeFunctionReference<"query">("relationshipState:listByPriorityTier"),
  relationshipStateUpsertFromSignals: makeFunctionReference<"mutation">("relationshipState:upsertFromSignals"),

  mediaGenerateUploadUrl: makeFunctionReference<"mutation">("media:generateUploadUrl"),
  mediaRegisterAsset: makeFunctionReference<"mutation">("media:registerAsset"),
  mediaFindAssetByContentHash: makeFunctionReference<"query">("media:findAssetByContentHash"),
  mediaRegisterAssetIfMissing: makeFunctionReference<"mutation">("media:registerAssetIfMissing"),
  mediaDedupeStickerExactPass: makeFunctionReference<"mutation">("media:dedupeStickerExactPass"),
  mediaUpsertAssetContext: makeFunctionReference<"mutation">("media:upsertAssetContext"),
  mediaListStickerAssetsNeedingContext: makeFunctionReference<"query">("media:listStickerAssetsNeedingContext"),
  mediaListAssets: makeFunctionReference<"query">("media:listAssets"),
  mediaCleanupStatusRetention: makeFunctionReference<"mutation">("media:cleanupStatusRetention"),
  mediaCompactContextWindows: makeFunctionReference<"mutation">("media:compactContextWindows"),
  mediaGetEnabledByKind: makeFunctionReference<"query">("media:getEnabledByKind"),
  mediaGetBestGeneratedMemeForThread: makeFunctionReference<"query">("media:getBestGeneratedMemeForThread"),
  mediaGetBestUploadedMemeFallback: makeFunctionReference<"query">("media:getBestUploadedMemeFallback"),
  mediaGetAssetDownloadUrl: makeFunctionReference<"query">("media:getAssetDownloadUrl"),
  mediaMarkAssetUsed: makeFunctionReference<"mutation">("media:markAssetUsed"),
  mediaToggleAsset: makeFunctionReference<"mutation">("media:toggleAsset"),
  mediaDeleteAsset: makeFunctionReference<"mutation">("media:deleteAsset"),

  groundingGetThreadGrounding: makeFunctionReference<"query">("grounding:getThreadGrounding"),
  groundingSaveThreadGrounding: makeFunctionReference<"mutation">("grounding:saveThreadGrounding"),
  inboundIngestHistorical: makeFunctionReference<"mutation">("inbound:ingestHistorical"),
  chatHistoryBackfillImport: makeFunctionReference<"action">("chatTools:historyBackfillImport"),
  chatExternalWebSearch: makeFunctionReference<"action">("chatTools:externalWebSearch"),
  chatPersonalConnectorsSearch: makeFunctionReference<"action">("chatTools:personalConnectorsSearch"),
  chatToolRouterPlan: makeFunctionReference<"action">("chatTools:toolRouterPlan"),
  codeGetPublishedWebhookProject: makeFunctionReference<"query">("code:getPublishedWebhookProject"),
  codeListActiveBehaviorExtensions: makeFunctionReference<"query">("code:listActiveBehaviorExtensions"),
  codeRecordProjectRun: makeFunctionReference<"mutation">("code:recordProjectRun"),
};

export type ConvexRefs = typeof convexRefs;
