import { makeFunctionReference } from "convex/server";

export const convexRefs = {
  queueList: makeFunctionReference<"query">("queue:list"),
  threadsList: makeFunctionReference<"query">("threads:list"),
  threadGet: makeFunctionReference<"query">("threads:get"),
  threadsGetEligibility: makeFunctionReference<"query">("threads:getEligibility"),
  followupsList: makeFunctionReference<"query">("followups:list"),
  backlogList: makeFunctionReference<"query">("backlog:list"),
  todosList: makeFunctionReference<"query">("todos:list"),
  rulesList: makeFunctionReference<"query">("rules:list"),
  settingsGet: makeFunctionReference<"query">("settings:get"),
  systemHealth: makeFunctionReference<"query">("system:health"),
  systemSetupStatus: makeFunctionReference<"query">("system:setupStatus"),
  contextConversationHistorySearch: makeFunctionReference<"query">("contextTools:conversationHistorySearch"),
  contextGetMessageEmbeddings: makeFunctionReference<"query">("contextTools:getMessageEmbeddings"),
  contextWindowDetection: makeFunctionReference<"query">("contextTools:contextWindowDetection"),
  contextWindowCleaning: makeFunctionReference<"query">("contextTools:contextWindowCleaning"),
  contextGetThreadOldestMessageForFetch: makeFunctionReference<"query">("contextTools:getThreadOldestMessageForFetch"),

  inboundIngest: makeFunctionReference<"mutation">("inbound:ingest"),
  draftSaveGenerated: makeFunctionReference<"mutation">("draft:saveGenerated"),
  draftSaveOrReplacePending: makeFunctionReference<"mutation">("draft:saveOrReplacePending"),
  draftCreateGuardrailHold: makeFunctionReference<"mutation">("draft:createGuardrailHold"),
  draftApprove: makeFunctionReference<"mutation">("draft:approve"),
  draftSnooze: makeFunctionReference<"mutation">("draft:snooze"),
  followupsConfirm: makeFunctionReference<"mutation">("followups:confirm"),
  backlogRefreshRecent: makeFunctionReference<"mutation">("backlog:refreshRecent"),
  backlogCreateDraft: makeFunctionReference<"mutation">("backlog:createDraft"),
  backlogSetImportanceOverride: makeFunctionReference<"mutation">("backlog:setImportanceOverride"),
  backlogSetRelationshipOverride: makeFunctionReference<"mutation">("backlog:setRelationshipOverride"),
  backlogSnooze: makeFunctionReference<"mutation">("backlog:snooze"),
  backlogUnsnooze: makeFunctionReference<"mutation">("backlog:unsnooze"),
  backlogIgnoreThread: makeFunctionReference<"mutation">("backlog:ignoreThread"),
  todosFromCandidate: makeFunctionReference<"mutation">("todos:fromCandidate"),
  rulesUpsertIgnoreRule: makeFunctionReference<"mutation">("rules:upsertIgnoreRule"),
  threadsUpsertMetadata: makeFunctionReference<"mutation">("threads:upsertMetadata"),

  outboxClaimDue: makeFunctionReference<"mutation">("outbox:claimDue"),
  outboxMarkTyping: makeFunctionReference<"mutation">("outbox:markTyping"),
  outboxGetSendDisposition: makeFunctionReference<"query">("outbox:getSendDisposition"),
  outboxSuppressForManualIntervention: makeFunctionReference<"mutation">("outbox:suppressForManualIntervention"),
  outboxHydrateAiOutreach: makeFunctionReference<"mutation">("outbox:hydrateAiOutreach"),
  outboxMarkSent: makeFunctionReference<"mutation">("outbox:markSent"),
  outboxMarkFailed: makeFunctionReference<"mutation">("outbox:markFailed"),

  systemPauseAutonomy: makeFunctionReference<"mutation">("system:pauseAutonomy"),
  systemResumeAutonomy: makeFunctionReference<"mutation">("system:resumeAutonomy"),
  systemRecordEvent: makeFunctionReference<"mutation">("system:recordEvent"),
  systemRecordProviderRun: makeFunctionReference<"mutation">("system:recordProviderRun"),
  systemUpsertSetupStatus: makeFunctionReference<"mutation">("system:upsertSetupStatus"),
  systemReportSetupListener: makeFunctionReference<"mutation">("system:reportSetupListener"),
  contextUpsertMessageEmbeddings: makeFunctionReference<"mutation">("contextTools:upsertMessageEmbeddings"),

  styleGetProfile: makeFunctionReference<"query">("style:getProfile"),
  styleSetMimicry: makeFunctionReference<"mutation">("style:setMimicry"),
  styleLearnFromHumorSignal: makeFunctionReference<"mutation">("style:learnFromHumorSignal"),
  personalityListProfiles: makeFunctionReference<"query">("personality:listProfiles"),
  personalityGetThreadSetting: makeFunctionReference<"query">("personality:getThreadSetting"),
  personalitySetThreadSetting: makeFunctionReference<"mutation">("personality:setThreadSetting"),
  personalityUpsertProfile: makeFunctionReference<"mutation">("personality:upsertProfile"),

  mediaGenerateUploadUrl: makeFunctionReference<"mutation">("media:generateUploadUrl"),
  mediaRegisterAsset: makeFunctionReference<"mutation">("media:registerAsset"),
  mediaListAssets: makeFunctionReference<"query">("media:listAssets"),
  mediaGetEnabledByKind: makeFunctionReference<"query">("media:getEnabledByKind"),
  mediaGetAssetDownloadUrl: makeFunctionReference<"query">("media:getAssetDownloadUrl"),
  mediaToggleAsset: makeFunctionReference<"mutation">("media:toggleAsset"),
  mediaDeleteAsset: makeFunctionReference<"mutation">("media:deleteAsset"),

  groundingGetThreadGrounding: makeFunctionReference<"query">("grounding:getThreadGrounding"),
  groundingSaveThreadGrounding: makeFunctionReference<"mutation">("grounding:saveThreadGrounding"),
  inboundIngestHistorical: makeFunctionReference<"mutation">("inbound:ingestHistorical"),
};

export type ConvexRefs = typeof convexRefs;
