import { makeFunctionReference } from "convex/server";

export const convexRefs = {
  queueList: makeFunctionReference<"query">("queue:list"),
  threadsList: makeFunctionReference<"query">("threads:list"),
  threadGet: makeFunctionReference<"query">("threads:get"),
  callsListByThread: makeFunctionReference<"query">("calls:listByThread"),
  callsHasRecentFallbackSend: makeFunctionReference<"query">("calls:hasRecentFallbackSend"),
  threadsGetEligibility: makeFunctionReference<"query">("threads:getEligibility"),
  threadsGetEligibilityByJid: makeFunctionReference<"query">("threads:getEligibilityByJid"),
  followupsList: makeFunctionReference<"query">("followups:list"),
  backlogList: makeFunctionReference<"query">("backlog:list"),
  todosList: makeFunctionReference<"query">("todos:list"),
  rulesList: makeFunctionReference<"query">("rules:list"),
  settingsGet: makeFunctionReference<"query">("settings:get"),
  systemHealth: makeFunctionReference<"query">("system:health"),
  systemSetupStatus: makeFunctionReference<"query">("system:setupStatus"),
  contextConversationHistorySearch: makeFunctionReference<"query">("contextTools:conversationHistorySearch"),
  contextGetMessageEmbeddings: makeFunctionReference<"query">("contextTools:getMessageEmbeddings"),
  contextWindowDetection: makeFunctionReference<"query">("contextTools:contextWindowDetection"),
  contextWindowCleaning: makeFunctionReference<"query">("contextTools:contextWindowCleaning"),
  contextGetThreadOldestMessageForFetch: makeFunctionReference<"query">("contextTools:getThreadOldestMessageForFetch"),
  chatMemorySearch: makeFunctionReference<"query">("chatTools:memorySearch"),
  chatConversationRecallQuery: makeFunctionReference<"query">("chatTools:conversationRecallQuery"),
  chatGetThreadStyleProfile: makeFunctionReference<"query">("chatTools:getThreadStyleProfile"),
  chatContactMemoryFactsList: makeFunctionReference<"query">("chatTools:contactMemoryFactsList"),
  chatPersonalConnectorsInternalSearch: makeFunctionReference<"query">("chatTools:personalConnectorsInternalSearch"),
  chatReplyStyleGuardrailCheck: makeFunctionReference<"query">("chatTools:replyStyleGuardrailCheck"),
  aiFeedbackGetThreadAdaptiveHints: makeFunctionReference<"query">("aiFeedback:getThreadAdaptiveHints"),
  aiFeedbackGetActiveTuningProfile: makeFunctionReference<"query">("aiFeedback:getActiveTuningProfile"),

  inboundIngest: makeFunctionReference<"mutation">("inbound:ingest"),
  inboundAttachMediaAsset: makeFunctionReference<"mutation">("inbound:attachMediaAsset"),
  draftSaveGenerated: makeFunctionReference<"mutation">("draft:saveGenerated"),
  draftSaveOrReplacePending: makeFunctionReference<"mutation">("draft:saveOrReplacePending"),
  draftCreateGuardrailHold: makeFunctionReference<"mutation">("draft:createGuardrailHold"),
  draftApprove: makeFunctionReference<"mutation">("draft:approve"),
  draftSnooze: makeFunctionReference<"mutation">("draft:snooze"),
  followupsConfirm: makeFunctionReference<"mutation">("followups:confirm"),
  backlogRefreshRecent: makeFunctionReference<"mutation">("backlog:refreshRecent"),
  backlogCreateDraft: makeFunctionReference<"mutation">("backlog:createDraft"),
  backlogSetImportanceOverride: makeFunctionReference<"mutation">("backlog:setImportanceOverride"),
  backlogSetRelationshipOverride: makeFunctionReference<"mutation">("backlog:setRelationshipOverride"),
  backlogSnooze: makeFunctionReference<"mutation">("backlog:snooze"),
  backlogUnsnooze: makeFunctionReference<"mutation">("backlog:unsnooze"),
  backlogIgnoreThread: makeFunctionReference<"mutation">("backlog:ignoreThread"),
  todosFromCandidate: makeFunctionReference<"mutation">("todos:fromCandidate"),
  rulesUpsertIgnoreRule: makeFunctionReference<"mutation">("rules:upsertIgnoreRule"),
  threadsUpsertMetadata: makeFunctionReference<"mutation">("threads:upsertMetadata"),
  threadsSetNightPause: makeFunctionReference<"mutation">("threads:setNightPause"),
  callsRecordEvent: makeFunctionReference<"mutation">("calls:recordEvent"),

  outboxClaimDue: makeFunctionReference<"mutation">("outbox:claimDue"),
  outboxMarkTyping: makeFunctionReference<"mutation">("outbox:markTyping"),
  outboxGetSendDisposition: makeFunctionReference<"query">("outbox:getSendDisposition"),
  outboxSuppressForManualIntervention: makeFunctionReference<"mutation">("outbox:suppressForManualIntervention"),
  outboxHydrateAiOutreach: makeFunctionReference<"mutation">("outbox:hydrateAiOutreach"),
  outboxHydrateAiStatus: makeFunctionReference<"mutation">("outbox:hydrateAiStatus"),
  outboxStageStatusReview: makeFunctionReference<"mutation">("outbox:stageStatusReview"),
  outboxRewriteClaimedMessage: makeFunctionReference<"mutation">("outbox:rewriteClaimedMessage"),
  outboxMarkSent: makeFunctionReference<"mutation">("outbox:markSent"),
  outboxMarkFailed: makeFunctionReference<"mutation">("outbox:markFailed"),

  systemPauseAutonomy: makeFunctionReference<"mutation">("system:pauseAutonomy"),
  systemResumeAutonomy: makeFunctionReference<"mutation">("system:resumeAutonomy"),
  systemRecordEvent: makeFunctionReference<"mutation">("system:recordEvent"),
  systemRecordProviderRun: makeFunctionReference<"mutation">("system:recordProviderRun"),
  systemRecordToolRun: makeFunctionReference<"mutation">("system:recordToolRun"),
  systemUpsertSetupStatus: makeFunctionReference<"mutation">("system:upsertSetupStatus"),
  systemReportSetupListener: makeFunctionReference<"mutation">("system:reportSetupListener"),
  contextUpsertMessageEmbeddings: makeFunctionReference<"mutation">("contextTools:upsertMessageEmbeddings"),
  chatRebuildThreadStyleProfile: makeFunctionReference<"mutation">("chatTools:rebuildThreadStyleProfile"),
  chatUpsertContactMemoryFact: makeFunctionReference<"mutation">("chatTools:upsertContactMemoryFact"),
  chatExtractContactMemoryFacts: makeFunctionReference<"mutation">("chatTools:extractContactMemoryFacts"),
  aiFeedbackRecordSignal: makeFunctionReference<"mutation">("aiFeedback:recordSignal"),
  aiFeedbackRecordCandidateEvals: makeFunctionReference<"mutation">("aiFeedback:recordCandidateEvals"),

  styleGetProfile: makeFunctionReference<"query">("style:getProfile"),
  styleGetStatusVoice: makeFunctionReference<"query">("style:getStatusVoice"),
  styleSetMimicry: makeFunctionReference<"mutation">("style:setMimicry"),
  styleLearnFromHumorSignal: makeFunctionReference<"mutation">("style:learnFromHumorSignal"),
  personalityListProfiles: makeFunctionReference<"query">("personality:listProfiles"),
  personalityGetThreadSetting: makeFunctionReference<"query">("personality:getThreadSetting"),
  personalitySetThreadSetting: makeFunctionReference<"mutation">("personality:setThreadSetting"),
  personalityUpsertProfile: makeFunctionReference<"mutation">("personality:upsertProfile"),
  romanceMorningGetThreadState: makeFunctionReference<"query">("romanceProtocol:getThreadState"),
  romanceMorningRecordHydration: makeFunctionReference<"mutation">("romanceProtocol:recordHydration"),

  mediaGenerateUploadUrl: makeFunctionReference<"mutation">("media:generateUploadUrl"),
  mediaRegisterAsset: makeFunctionReference<"mutation">("media:registerAsset"),
  mediaFindAssetByContentHash: makeFunctionReference<"query">("media:findAssetByContentHash"),
  mediaRegisterAssetIfMissing: makeFunctionReference<"mutation">("media:registerAssetIfMissing"),
  mediaDedupeStickerExactPass: makeFunctionReference<"mutation">("media:dedupeStickerExactPass"),
  mediaUpsertAssetContext: makeFunctionReference<"mutation">("media:upsertAssetContext"),
  mediaListStickerAssetsNeedingContext: makeFunctionReference<"query">("media:listStickerAssetsNeedingContext"),
  mediaListAssets: makeFunctionReference<"query">("media:listAssets"),
  mediaCleanupStatusRetention: makeFunctionReference<"mutation">("media:cleanupStatusRetention"),
  mediaCompactContextWindows: makeFunctionReference<"mutation">("media:compactContextWindows"),
  mediaGetEnabledByKind: makeFunctionReference<"query">("media:getEnabledByKind"),
  mediaGetBestGeneratedMemeForThread: makeFunctionReference<"query">("media:getBestGeneratedMemeForThread"),
  mediaGetBestUploadedMemeFallback: makeFunctionReference<"query">("media:getBestUploadedMemeFallback"),
  mediaGetAssetDownloadUrl: makeFunctionReference<"query">("media:getAssetDownloadUrl"),
  mediaMarkAssetUsed: makeFunctionReference<"mutation">("media:markAssetUsed"),
  mediaToggleAsset: makeFunctionReference<"mutation">("media:toggleAsset"),
  mediaDeleteAsset: makeFunctionReference<"mutation">("media:deleteAsset"),

  groundingGetThreadGrounding: makeFunctionReference<"query">("grounding:getThreadGrounding"),
  groundingSaveThreadGrounding: makeFunctionReference<"mutation">("grounding:saveThreadGrounding"),
  inboundIngestHistorical: makeFunctionReference<"mutation">("inbound:ingestHistorical"),
  chatHistoryBackfillImport: makeFunctionReference<"action">("chatTools:historyBackfillImport"),
  chatExternalWebSearch: makeFunctionReference<"action">("chatTools:externalWebSearch"),
  chatPersonalConnectorsSearch: makeFunctionReference<"action">("chatTools:personalConnectorsSearch"),
  chatToolRouterPlan: makeFunctionReference<"action">("chatTools:toolRouterPlan"),
};

export type ConvexRefs = typeof convexRefs;
