import makeWASocket, { DisconnectReason, useMultiFileAuthState } from "baileys";
import pino from "pino";
import { ConvexHttpClient } from "convex/browser";
import { convexRefs } from "../lib/convex-refs";
import { generateReplyWithFallback, estimateDelayAndTyping } from "./ai";
import { extractTextFromMessage, getSenderJid, getThreadJid } from "./whatsapp";

const logger = pino({
  name: "slm-worker",
  level: process.env.LOG_LEVEL || "info",
});

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function createConvexClient() {
  const url = process.env.CONVEX_URL || process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!url) {
    throw new Error("Missing CONVEX_URL or NEXT_PUBLIC_CONVEX_URL for worker");
  }
  return new ConvexHttpClient(url);
}

async function run() {
  const convex = createConvexClient();
  const workerId = process.env.SLM_WORKER_ID || `worker-${process.pid}`;
  const authPath = process.env.WHATSAPP_AUTH_PATH || ".wa_auth";

  // `useMultiFileAuthState` is a Baileys API, not a React hook.
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { state, saveCreds } = await useMultiFileAuthState(authPath);

  let processingOutbox = false;
  let sock = makeWASocket({
    auth: state,
    printQRInTerminal: true,
    browser: ["Social Life Manager", "Chrome", "1.0.0"],
  });

  const attachListeners = () => {
    sock.ev.on("creds.update", saveCreds);

    sock.ev.on("connection.update", async (update) => {
      if (update.connection === "close") {
        const statusCode = (update.lastDisconnect?.error as { output?: { statusCode?: number } } | undefined)
          ?.output?.statusCode;

        const shouldReconnect = statusCode !== DisconnectReason.loggedOut;
        logger.warn({ statusCode, shouldReconnect }, "WhatsApp connection closed");

        if (shouldReconnect) {
          sock = makeWASocket({
            auth: state,
            printQRInTerminal: true,
            browser: ["Social Life Manager", "Chrome", "1.0.0"],
          });
          attachListeners();
        }
      }

      if (update.connection === "open") {
        logger.info("WhatsApp connection established");
      }
    });

    sock.ev.on("messages.upsert", async (event) => {
      if (event.type !== "notify") {
        return;
      }

      for (const message of event.messages) {
        if (message.key.fromMe) {
          continue;
        }

        const text = extractTextFromMessage(message.message);
        const threadJid = getThreadJid(message.key);
        const senderJid = getSenderJid(message.key);

        if (!text || !threadJid || !senderJid) {
          continue;
        }

        const ingest = (await convex.mutation(convexRefs.inboundIngest, {
          threadJid,
          senderJid,
          senderTitle: message.pushName,
          text,
          isGroup: threadJid.endsWith("@g.us"),
          whatsappMessageId: message.key.id,
          messageAt: Number(message.messageTimestamp || Date.now()),
          skipDraftGeneration: true,
        })) as {
          threadId: string;
          messageId: string;
          ignored: boolean;
        };

        if (ingest.ignored) {
          logger.info({ threadJid }, "Inbound ignored by rules");
          continue;
        }

        const threadContext = (await convex.query(convexRefs.threadGet, {
          threadId: ingest.threadId,
        })) as
          | {
              messages: Array<{ direction: "inbound" | "outbound"; text: string }>;
              memory?: { styleNotes?: string[] } | null;
            }
          | null;

        const historyLines = (threadContext?.messages || []).slice(-12).map((m) => {
          return `${m.direction === "inbound" ? "Them" : "Me"}: ${m.text}`;
        });

        const styleHints = threadContext?.memory?.styleNotes || [];

        const ai = await generateReplyWithFallback({
          inboundText: text,
          historyLines,
          styleHints,
        });

        if (ai.guardrailBlocked) {
          await convex.mutation(convexRefs.draftCreateGuardrailHold, {
            threadId: ingest.threadId,
            sourceMessageId: ingest.messageId,
            reason: ai.guardrailReason || "Blocked by guardrail",
          });
          continue;
        }

        const timing = estimateDelayAndTyping(ai.text);
        const draftId = (await convex.mutation(convexRefs.draftSaveGenerated, {
          threadId: ingest.threadId,
          sourceMessageId: ingest.messageId,
          text: ai.text,
          provider: ai.provider,
          confidence: ai.provider === "heuristic" ? 0.58 : 0.78,
          delayMs: timing.delayMs,
          typingMs: timing.typingMs,
          reason: "Generated by worker AI pipeline",
        })) as string;

        await convex.mutation(convexRefs.systemRecordProviderRun, {
          threadId: ingest.threadId,
          draftId,
          provider: ai.provider,
          model: ai.model,
          latencyMs: ai.latencyMs,
          status: "success",
        });

        const health = (await convex.query(convexRefs.systemHealth, {})) as {
          config?: { autonomyPaused?: boolean };
        };

        if (!health?.config?.autonomyPaused) {
          await convex.mutation(convexRefs.draftApprove, {
            draftId,
          });
        }
      }
    });
  };

  attachListeners();

  const pollOutbox = async () => {
    if (processingOutbox) {
      return;
    }

    processingOutbox = true;
    try {
      const claimed = (await convex.mutation(convexRefs.outboxClaimDue, {
        workerId,
        limit: 8,
      })) as Array<{
        outboxId: string;
        jid: string;
        messageText: string;
        typingMs: number;
      }>;

      for (const item of claimed) {
        try {
          await sock.sendPresenceUpdate("composing", item.jid);
          await convex.mutation(convexRefs.outboxMarkTyping, { outboxId: item.outboxId });
          await sleep(item.typingMs);
          const sent = await sock.sendMessage(item.jid, { text: item.messageText });
          await sock.sendPresenceUpdate("paused", item.jid);

          await convex.mutation(convexRefs.outboxMarkSent, {
            outboxId: item.outboxId,
            whatsappMessageId: sent?.key?.id,
          });
        } catch (error) {
          const err = error instanceof Error ? error.message : String(error);
          await convex.mutation(convexRefs.outboxMarkFailed, {
            outboxId: item.outboxId,
            error: err,
          });
        }
      }
    } finally {
      processingOutbox = false;
    }
  };

  const intervalMs = Number(process.env.SLM_OUTBOX_POLL_MS || 3000);
  setInterval(() => {
    void pollOutbox();
  }, intervalMs);

  logger.info({ workerId, intervalMs }, "Social Life Manager worker started");
}

void run().catch((error) => {
  logger.error({ err: error }, "Worker crashed");
  process.exit(1);
});
