// Auto-generated by scripts/pidgin-lexicon-promote.ts
// Do not edit manually.

export const GENERATED_PIDGIN_STRONG_TOKENS: string[] = [
  "govnorship"
];
export const GENERATED_PIDGIN_EXTENDED_TOKENS: string[] = [
  "how now",
  "small-small"
];
export const GENERATED_PIDGIN_WEAK_TOKENS: string[] = [
  "na wa o"
];

export const GENERATED_PIDGIN_LEXICON_METADATA = {
  "generatedAt": "2026-04-08T12:16:40.602Z",
  "sourceCandidatesFile": "data/pidgin-lexicon-candidates.json",
  "sourceApprovalsFile": "data/pidgin-lexicon-approvals.json",
  "promoted": {
    "total": 4,
    "auto": 1,
    "manual": 3,
    "strong": 1,
    "extended": 2,
    "weak": 1
  }
};
