import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

type CliArgs = {
  write: boolean;
  candidates: string;
  approvals: string;
  out: string;
};

type CandidateEntry = {
  term: string;
  bucket: "strong" | "extended" | "weak" | "unknown";
  safety: "safe" | "review" | "blocked";
  sourceCategories?: string[];
  score?: number;
};

type CandidateReport = {
  highConfidence?: CandidateEntry[];
  reviewQueue?: CandidateEntry[];
  lowConfidence?: CandidateEntry[];
};

type ApprovalConfig = {
  approved?: string[];
  rejected?: string[];
};

const AMBIGUOUS_CATEGORY_PATTERN = /\b(proper nouns?|trademarks?|offensive|derogatory)\b/i;
const AMBIGUOUS_TERM_PATTERN = /\b(igbo)\b/i;

function parseArgs(argv: string[]): CliArgs {
  let write = false;
  let candidates = "data/pidgin-lexicon-candidates.json";
  let approvals = "data/pidgin-lexicon-approvals.json";
  let out = "shared/pidgin-lexicon-generated.ts";

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--write") {
      write = true;
      continue;
    }
    if (arg === "--candidates") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("Missing value for --candidates");
      }
      candidates = value;
      index += 1;
      continue;
    }
    if (arg === "--approvals") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("Missing value for --approvals");
      }
      approvals = value;
      index += 1;
      continue;
    }
    if (arg === "--out") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("Missing value for --out");
      }
      out = value;
      index += 1;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  return { write, candidates, approvals, out };
}

function normalizeTerm(term: string) {
  return term.trim().toLowerCase();
}

async function readJson<T>(path: string) {
  const raw = await readFile(path, "utf8");
  return JSON.parse(raw) as T;
}

async function loadExistingGenerated(outPath: string) {
  try {
    const moduleUrl = `${pathToFileURL(outPath).href}?ts=${Date.now()}`;
    const generatedModule = (await import(moduleUrl)) as {
      GENERATED_PIDGIN_STRONG_TOKENS?: string[];
      GENERATED_PIDGIN_EXTENDED_TOKENS?: string[];
      GENERATED_PIDGIN_WEAK_TOKENS?: string[];
    };
    return {
      strong: (generatedModule.GENERATED_PIDGIN_STRONG_TOKENS || []).map(normalizeTerm).filter(Boolean),
      extended: (generatedModule.GENERATED_PIDGIN_EXTENDED_TOKENS || []).map(normalizeTerm).filter(Boolean),
      weak: (generatedModule.GENERATED_PIDGIN_WEAK_TOKENS || []).map(normalizeTerm).filter(Boolean),
    };
  } catch {
    return {
      strong: [] as string[],
      extended: [] as string[],
      weak: [] as string[],
    };
  }
}

function toTermSet(items: string[] | undefined) {
  return new Set((items || []).map((entry) => normalizeTerm(entry)).filter(Boolean));
}

function buildGeneratedModule(args: {
  strongTerms: string[];
  extendedTerms: string[];
  weakTerms: string[];
  candidatesPath: string;
  approvalsPath: string;
  autoCount: number;
  manualCount: number;
}) {
  const { strongTerms, extendedTerms, weakTerms } = args;
  const total = strongTerms.length + extendedTerms.length + weakTerms.length;
  const payload = {
    generatedAt: new Date().toISOString(),
    sourceCandidatesFile: args.candidatesPath,
    sourceApprovalsFile: args.approvalsPath,
    promoted: {
      total,
      auto: args.autoCount,
      manual: args.manualCount,
      strong: strongTerms.length,
      extended: extendedTerms.length,
      weak: weakTerms.length,
    },
  };

  return `// Auto-generated by scripts/pidgin-lexicon-promote.ts
// Do not edit manually.

export const GENERATED_PIDGIN_STRONG_TOKENS: string[] = ${JSON.stringify(strongTerms, null, 2)};
export const GENERATED_PIDGIN_EXTENDED_TOKENS: string[] = ${JSON.stringify(extendedTerms, null, 2)};
export const GENERATED_PIDGIN_WEAK_TOKENS: string[] = ${JSON.stringify(weakTerms, null, 2)};

export const GENERATED_PIDGIN_LEXICON_METADATA = ${JSON.stringify(payload, null, 2)};\n`;
}

function isAutoPromotable(entry: CandidateEntry) {
  if (entry.safety !== "safe" || entry.bucket !== "strong") {
    return false;
  }
  if (AMBIGUOUS_TERM_PATTERN.test(entry.term)) {
    return false;
  }
  const categories = entry.sourceCategories || [];
  return !categories.some((category) => AMBIGUOUS_CATEGORY_PATTERN.test(category));
}

async function ensureApprovalsFile(path: string) {
  try {
    await readFile(path, "utf8");
  } catch {
    const initial: ApprovalConfig = {
      approved: [],
      rejected: [],
    };
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, `${JSON.stringify(initial, null, 2)}\n`, "utf8");
  }
}

async function run() {
  const args = parseArgs(process.argv.slice(2));
  const candidatesPath = resolve(process.cwd(), args.candidates);
  const approvalsPath = resolve(process.cwd(), args.approvals);
  const outPath = resolve(process.cwd(), args.out);

  await ensureApprovalsFile(approvalsPath);

  const report = await readJson<CandidateReport>(candidatesPath);
  const approvals = await readJson<ApprovalConfig>(approvalsPath);
  const approved = toTermSet(approvals.approved);
  const rejected = toTermSet(approvals.rejected);
  const existing = await loadExistingGenerated(outPath);
  const previouslyPromoted = new Set([...existing.strong, ...existing.extended, ...existing.weak]);

  const pool = [...(report.highConfidence || []), ...(report.reviewQueue || []), ...(report.lowConfidence || [])];
  const deduped = new Map<string, CandidateEntry>();
  for (const entry of pool) {
    const term = normalizeTerm(entry.term || "");
    if (!term || deduped.has(term)) {
      continue;
    }
    deduped.set(term, { ...entry, term });
  }

  const strongTerms = new Set(existing.strong.filter((term) => !rejected.has(term)));
  const extendedTerms = new Set(existing.extended.filter((term) => !rejected.has(term)));
  const weakTerms = new Set(existing.weak.filter((term) => !rejected.has(term)));
  let autoCount = 0;
  let manualCount = 0;

  for (const entry of deduped.values()) {
    const term = entry.term;
    if (!term || rejected.has(term) || entry.safety === "blocked") {
      continue;
    }

    const manuallyApproved = approved.has(term);
    const autoApproved = isAutoPromotable(entry);
    if (!manuallyApproved && !autoApproved) {
      continue;
    }

    if (!previouslyPromoted.has(term)) {
      if (manuallyApproved) {
        manualCount += 1;
      } else if (autoApproved) {
        autoCount += 1;
      }
    }

    strongTerms.delete(term);
    extendedTerms.delete(term);
    weakTerms.delete(term);

    if (entry.bucket === "strong") {
      strongTerms.add(term);
      continue;
    }
    if (entry.bucket === "extended") {
      extendedTerms.add(term);
      continue;
    }
    if (entry.bucket === "weak") {
      weakTerms.add(term);
      continue;
    }
  }

  const strongList = [...strongTerms].sort((a, b) => a.localeCompare(b));
  const extendedList = [...extendedTerms].sort((a, b) => a.localeCompare(b));
  const weakList = [...weakTerms].sort((a, b) => a.localeCompare(b));

  const generated = buildGeneratedModule({
    strongTerms: strongList,
    extendedTerms: extendedList,
    weakTerms: weakList,
    candidatesPath: args.candidates,
    approvalsPath: args.approvals,
    autoCount,
    manualCount,
  });

  if (args.write) {
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, generated, "utf8");
    console.log(`Wrote generated lexicon module to ${outPath}`);
  } else {
    console.log(
      `Dry run: would promote ${strongList.length + extendedList.length + weakList.length} terms (auto=${autoCount}, manual=${manualCount}).`,
    );
    const preview = [...strongList, ...extendedList, ...weakList].slice(0, 80);
    console.log(preview.join(", "));
    console.log("Run with --write to generate shared/pidgin-lexicon-generated.ts");
  }
}

void run().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
